### ISSUE TITLE
"Account doesn't exist" Notification upon Login

### ISSUE THREAD

**Issue by agoluoglu** [gcivil-nyu-org/INET-Monday-Fall2023-Team-4#137]
Tried logging in with incorrect password. Then logged in successfully. Then the welcome page it directs to says my account doesn't exist and that I should sign up even though I am logged into an account.
<img width="1522" alt="Screenshot 2023-11-18 at 1 45 30 AM" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-4/assets/119933910/4b00e6b4-c8e9-4e76-9b64-e20e40e6b1f1">

**Comment by jayjayh** [comment]
This might happen if you failed to log in with some credentials and then enter the right credentials. the messages stack on top of each other instead of only displaying the latest one
