### ISSUE TITLE
As a developer, I want to push the library information to the application database so that the library view pages have data to pull from.

### ISSUE THREAD

**Issue by zrodriguez** [gcivil-nyu-org/INET-Monday-Fall2023-Team-4#20]
**User story**
As a developer, I want to push the library information to the application database so that the library view pages have data to pull from.

**Acceptance criteria**
Consolidated data from dataset and manually data for NYU libraries. Data is based in to application database. 

**Definition of Done**
Access and ability for the application to retrieve library information from database.

**Comment by zrodriguez** [comment]
Library Dataset in Check Out Google Drive.

**Comment by FranckyXue** [comment]
We figured out a way to connect with mysql database and import libraries data and show it on the page
