### ISSUE TITLE
As a developer, I want to debug the email confirmation process so that the users' emails are validated.

### ISSUE THREAD

**Issue by zrodriguez** [gcivil-nyu-org/INET-Monday-Fall2023-Team-4#25]
**User story**
As a developer, I want to debug the email confirmation process so that the users' emails are validated.

**Acceptance criteria**
Send validation email to user and have user input the validation code. 

**Definition of Done**
Automated test.

**Comment by jayjayh** [comment]
The email can now be sent and the verification code is also generated and should be working

**Comment by jayjayh** [comment]
need to pull the current changes before pushing changes

**Comment by jayjayh** [comment]
PR created for master branch
