### ISSUE TITLE
As developer, I want a database deployed so that I can perform CRUD operations to data needed for the application.

### ISSUE THREAD

**Issue by rg4352** [gcivil-nyu-org/INET-Monday-Fall2023-Team-4#27]
**User story**
As developer, I want a database deployed so that I can perform CRUD operations to data needed for the application.
**Acceptance criteria**
A deployed database instance connected with AWS and the github repository 
**Definition of Done**
A database has been deployed on AWS and is accessible to the developers working on the CheckOut repository

**Comment by jayjayh** [comment]
The deployed db can now be accessed by our django app

**Comment by jayjayh** [comment]
we just need to deploy the new settings file and have the environment variables set up on elastic beanstalk
