### ISSUE TITLE
As an unregistered user, I want to be able to register for the application so that I can interact with the rest of the features. 

### ISSUE THREAD

**Issue by xxzz-tt** [gcivil-nyu-org/INET-Monday-Fall2023-Team-4#6]
**User story**
As a general user, I want to be able to register for the application so that I can interact with the rest of the features. Without an account, the user should only be able to view public libraries and book clubs. 

**Acceptance criteria**
Collect name, valid email address, and password. OTP. Hash/salted password. User added to database. When user does not provide strong password, return error page.

**Definition of Done**
Users can sign in and view the account page. Ability to subscribe (eventually implemented). User added to database. Unit tests. Automated tests pass.

**Comment by jayjayh** [comment]
made some changes to the form and views. should be able to register and login now

**Comment by jayjayh** [comment]
need someone to review the code changes and approve the pull request
